name: Build C++ Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt update && sudo apt install g++ -y

      - name: Compile C++ code
        run: g++ main.cpp --std=c++17 -o MyFave
