name: Build C++

on:
  push:
    branches: "**"
  pull_request:
    branches: [ main ]

jobs:
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: g++ main.cpp --std=c++17 -o MyFave